FROM python:3.9-slim

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt

# Install system dependencies for OpenCV and AI
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 ffmpeg

# Install Python packages
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

# Run the FastAPI server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "7860"]